import type { Lens } from './types';

export const lenses: Lens[] = [
  {
    id: 'AL-001',
    name: 'Appleye Wide-Angle 4K',
    sensorSize: '1/2.3"',
    efl: 3.8,
    maxImageCircle: 7.9,
    fNo: 2.8,
    fovD: 102,
    fovH: 90,
    fovV: 59,
    ttl: 22.5,
    tvDistortion: -1.5,
    relativeIllumination: 65,
    chiefRayAngle: 34,
    mountType: 'M12',
    lensStructure: '8E+IR',
    price: 150,
  },
  {
    id: 'AL-002',
    name: 'Appleye Telephoto Zoom',
    sensorSize: '1/1.8"',
    efl: 12.0,
    maxImageCircle: 9.0,
    fNo: 4.0,
    fovD: 40,
    fovH: 32,
    fovV: 24,
    ttl: 45.0,
    tvDistortion: 0.8,
    relativeIllumination: 70,
    chiefRayAngle: 18,
    mountType: 'C-Mount',
    lensStructure: '10G',
    price: 320,
  },
  {
    id: 'AL-003',
    name: 'Appleye Standard Prime',
    sensorSize: '2/3"',
    efl: 8.5,
    maxImageCircle: 11.0,
    fNo: 2.0,
    fovD: 72,
    fovH: 60,
    fovV: 47,
    ttl: 30.1,
    tvDistortion: -0.5,
    relativeIllumination: 75,
    chiefRayAngle: 25,
    mountType: 'CS-Mount',
    lensStructure: '6G+2P',
    price: 210,
  },
  {
    id: 'AL-004',
    name: 'Appleye Fisheye 360',
    sensorSize: '1/3"',
    efl: 1.5,
    maxImageCircle: 6.0,
    fNo: 2.2,
    fovD: 185,
    fovH: 185,
    fovV: 185,
    ttl: 18.0,
    tvDistortion: -25.0,
    relativeIllumination: 50,
    chiefRayAngle: 60,
    mountType: 'M12',
    lensStructure: '9E',
    price: 180,
  },
  {
    id: 'AL-005',
    name: 'Appleye Macro Focus',
    sensorSize: '1/2.5"',
    efl: 6.0,
    maxImageCircle: 7.2,
    fNo: 3.2,
    fovD: 65,
    fovH: 54,
    fovV: 41,
    ttl: 25.5,
    tvDistortion: 0.2,
    relativeIllumination: 80,
    chiefRayAngle: 28,
    mountType: 'Custom',
    lensStructure: '7G+IR',
    price: 250,
  },
  {
    id: 'AL-006',
    name: 'Appleye Compact Pro',
    sensorSize: '1/2.7"',
    efl: 4.2,
    maxImageCircle: 6.7,
    fNo: 2.4,
    fovD: 88,
    fovH: 75,
    fovV: 50,
    ttl: 20.0,
    tvDistortion: -0.8,
    relativeIllumination: 72,
    chiefRayAngle: 30,
    mountType: 'M12',
    lensStructure: '5G+2P+IR',
    price: 135,
  },
  {
    id: 'AL-007',
    name: 'Appleye Industrial C-Mount',
    sensorSize: '1"',
    efl: 25.0,
    maxImageCircle: 16.0,
    fNo: 1.8,
    fovD: 35,
    fovH: 28,
    fovV: 21,
    ttl: 55.2,
    tvDistortion: 0.1,
    relativeIllumination: 85,
    chiefRayAngle: 12,
    mountType: 'C-Mount',
    lensStructure: '12G',
    price: 550,
  },
  {
    id: 'AL-008',
    name: 'Appleye Varifocal',
    sensorSize: '1/2"',
    efl: 5.0, // Represents the lower end of the range
    maxImageCircle: 8.0,
    fNo: 3.5,
    fovD: 80,
    fovH: 66,
    fovV: 51,
    ttl: 38.0,
    tvDistortion: -1.2,
    relativeIllumination: 68,
    chiefRayAngle: 22,
    mountType: 'CS-Mount',
    lensStructure: '8G+3P',
    price: 420,
  },
  {
    id: 'AL-009',
    name: 'Appleye Low-Light King',
    sensorSize: '1/1.7"',
    efl: 10.0,
    maxImageCircle: 9.5,
    fNo: 1.4,
    fovD: 55,
    fovH: 44,
    fovV: 33,
    ttl: 35.0,
    tvDistortion: -0.3,
    relativeIllumination: 78,
    chiefRayAngle: 20,
    mountType: 'C-Mount',
    lensStructure: '9G+IR',
    price: 480,
  },
  {
    id: 'AL-010',
    name: 'Appleye Board Lens 6mm',
    sensorSize: '1/4"',
    efl: 6.0,
    maxImageCircle: 4.5,
    fNo: 2.0,
    fovD: 48,
    fovH: 39,
    fovV: 29,
    ttl: 15.0,
    tvDistortion: 0.5,
    relativeIllumination: 70,
    chiefRayAngle: 38,
    mountType: 'M12',
    lensStructure: '4G',
    price: 80,
  },
];

export const SENSOR_SIZES = [...new Set(lenses.map(l => l.sensorSize))].sort();
export const MOUNT_TYPES = [...new Set(lenses.map(l => l.mountType))].sort();
